version: "3.9"

x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "3"
  driver: json-file

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    logging: *default-logging
    depends_on:
      - mongodb
    env_file:
      - ./.env
    ports:
      - "3001:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    logging: *default-logging
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db_data:/data/db

volumes:
  db_data: